# Generated by Django 4.2.1 on 2023-06-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='car',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='client',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
