# Generated by Django 4.2.1 on 2023-06-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_cars_rent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
