# Generated by Django 4.2.1 on 2023-06-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_cars_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='full_name',
        ),
    ]
