# Generated by Django 4.2.1 on 2023-06-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_person_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
