# Generated by Django 4.2.1 on 2023-06-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.BigIntegerField(default='050505'),
            preserve_default=False,
        ),
    ]
